### ISSUE TITLE
could not build module XAspect

### ISSUE THREAD

**Issue by liLeiBest** [xareelee/XAspect#6]
I use cocoapods private library management project, when I am in the profile file configuration use_frameworks, then # import "XAspect. h" prompt "could not build the module XAspect".Because in XACrystallization. h file, # include < map > prompt "map file not found".
Cocoapods version 1.2.0. Beta. 1.
Waiting for help, thank you.

**Comment by xareelee** [comment]
Really thanks for your support and report.

This problem is due to using `use_frameworks!` while XAspect includes C++ headers. If you need to use `use_frameworks!`, try to install XAspect manually. 

This issue is possible to be fixed by finding a way to make C++ code can be wrapped in the dynamic framework using cocoapods, or re-writing XAspect using pure C or Objective-C instead of the C++ part. 

Currently, XAspect is not going to update if there is no fundamental or severe bug/issue. You may send a pull request if you have a fix about this issue.
